services:
  app:
    build: .
    image: ${DOCKER_USERNAME}/server:latest  # .env 파일의 변수 사용
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./logs:/app/logs  # 개발용 로그 볼륨 마운트
