spring:
  jackson:
    time-zone: Asia/Seoul
  datasource: # AWS RDS
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul         # DB 시간대 강제 지정
    hibernate:
      ddl-auto: create
    generate-ddl: false
  sql:
    init:
      mode: never
