name: Java CD

on:
  pull_request:
    branches: [ develop ]
    # 다음 파일들이 변경되었을 때는 워크플로우를 실행하지 않음
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 워크플로우가 실행되는 러너(가상 머신)에 해당 리포지토리의 코드를 클론하기 위해 사용
      - name: Checkout code
        uses: actions/checkout@v3

      # Gradle 의존성에 대한 캐싱 추가 (매 빌드마다 의존성을 다시 다운로드하게 되어 빌드 시간이 길어지는 걸 방지)
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/gradle-wrapper.properties') }}

      # 2) JDK 17 버전 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4) gradlew 실행 권한 부여 및 빌드 시작
      - name: Grant gradlew permission and build
        run: |
          chmod +x gradlew
          ./gradlew clean build

      # 5) Docker Hub 로그인 (프라이빗 레포지토리 접근)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6) Docker Compose 빌드 및 푸시 (이미지 이름 명시)
      - name: Build and push with Docker Compose
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker compose -f docker-compose-dev.yml build
          docker compose -f docker-compose-dev.yml push

      # 7) docker-compose-dev.yml 파일 EC2로 복사
      - name: Copy compose files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: |
            docker-compose-dev.yml
          target: "~"

      # 8) EC2에서 Docker Compose 실행 및 배포
      - name: Deploy to EC2 and start containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
            # EC2에서 기존 컨테이너를 중지하고 삭제 (선택)
            docker compose -f ~/docker-compose-dev.yml down || true

            # EC2에서 Docker Compose를 실행하면서 .env 파일을 사용하도록 --env-file 옵션 추가
            docker compose -f ~/docker-compose-dev.yml --env-file /home/ubuntu/.env up -d --remove-orphans
            
            # 불필요한 Docker 이미지 정리
            docker image prune -af  # 불필요한 이미지 정리 (선택)
